server:
  port: 8081

spring:
  application:
    name: MovieRentalDemo
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:~/test
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver

graphql:
  servlet:
    enabled: true
    mapping: /graphql

